name: Sync Python to GitLab

on:
  push:
    paths:
      - 'python/**'
      - '.github/workflows/sync-python.yml'

jobs:
  sync:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Push subtree to GitLab
        run: |
          git config user.name "github-bot"
          git config user.email "shapkin.alexandr.sergeevich@gmail.com"
          git remote add gitlab https://oauth2:${{ secrets.GITLAB_TOKEN }}@gitlab.alexandrshapkin.ru/AlexandrShapkin/python-multistack-lab.git
          git push gitlab `git subtree split --prefix=python main`:main --force
